stages:
  - build

variables:
  DOCKER_BUILDKIT: "1"
  DOCKER_TLS_CERTDIR: "/certs"

build-and-push:
  stage: build
  image: docker:27-cli
  services:
    - docker:27-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker context create tls-env
    - docker buildx create --name ci-builder --use tls-env
    - docker buildx inspect --bootstrap
  script:
  script:
    - |
      docker buildx build \
        --platform linux/amd64 \
        --push \
        --cache-from type=registry,ref=$CI_REGISTRY_IMAGE:buildcache \
        --cache-to type=registry,ref=$CI_REGISTRY_IMAGE:buildcache,mode=max \
        --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
        --tag "$CI_REGISTRY_IMAGE:latest" \
        .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
